name: Containerizing a Docker Image of a simple Spring Boot app using GitHub Actions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_containerize:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          mvn clean compile DskipTests=true
          mvn clean package DskipTests=true